### ISSUE TITLE
Update from 2.1.0 to 3.1.6 doesn't work

### ISSUE THREAD

**Issue by DanielBakovic** [ThemeAvenue/Awesome-Support#131]
Hi,
On one of our shops we use Awesome Support 2.1.0 which we have purchased on Codecanyon. We tried the automatic update to 3.1.6 but now all of our support tickets (764) are gone.

**Comment by julien731** [comment]
Hi Daniel,

You can't update 2.x to 3.x with automatic update. Actually you were not supposed to have the auto update at all in the WP dashboard. That's strange.

In order to upgrade to v3, a specific script is needed and we're still working on it. Meanwhile, you will need to downgrade to v2 in order to get your tickets back. It's not lost, you just can't see it with v3.

**Comment by DanielBakovic** [comment]
Just wondering how is the progress on the migration script/plugin. You announced it last year: https://themeavenue.net/why-awesome-support-free/

**Comment by julien731** [comment]
Indeed it's been a long time. The script is still under development. In order to make the migration possible we've had to develop new addons for version 3 first which postponed the script itself. We're currently working on it and hope to release it next month.
