### ISSUE TITLE
Styling issue - dashboard - product page - unnessessary description column

### ISSUE THREAD

**Issue by Ninos** [ThemeAvenue/Awesome-Support#65]
In /edit-tags.php?taxonomy=product&post_type=ticket there's a hidden column with the products description. If you have a description for the woocommerce product, your rows'll get very height.

I would remove this column...

**Comment by julien731** [comment]
I am not sure which column you're talking about but one thing I know is that there is an issue with the current version of WooCommerce and it's caused by WooCommerce. We already had it resolved and it will be fixed with next WC version. Are you seeing the "weird" table with lost of custom columns in the taxonomy screen?

**Comment by Ninos** [comment]
Yes I think we're talking about the same bug. In the product taxonomy screen the description column is missing (not visible) but exists. If you have a product description for the listed term, your style get broken (to high row).

Attached two screenshots..
![screenshot - 65 - 01](https://cloud.githubusercontent.com/assets/1012403/5854418/dd151baa-a22d-11e4-9ccd-26bea3d56748.png)
![screenshot - 65 - 02](https://cloud.githubusercontent.com/assets/1012403/5854419/dd1737d2-a22d-11e4-8684-fcc8a72afeff.png)

**Comment by julien731** [comment]
Alright. I know this bug. WooCommerce shouldn't add its custom things to our taxonomy page. It had been fixed by @bryceadams who's working with WooCommerce. I believe the fix was already pushed to master.

**Comment by Ninos** [comment]
Ah ok, thx :)
