### ISSUE TITLE
[woocommerce compatibility] - Fatal error on wp-admin - Call to a member function is_main_query()

### ISSUE THREAD

**Issue by Ninos** [ThemeAvenue/Awesome-Support#72]
With the newest woocommerce version 2.3.0-rc1 on /wp-admin/ I get following error:
```
Fatal error: Call to a member function is_main_query() on a non-object in /htdocs/wp-includes/query.php on line 730
```

**Comment by d4b** [comment]
Version 2.3.2 of the problem still exists.

**Comment by julien731** [comment]
The issue is caused by [`wpas_list_pages()`](https://github.com/ThemeAvenue/Awesome-Support/blob/master/includes/admin/settings/functions-settings.php#L8) that's used in the general and advanced settings.

Those settings are hooked on the filter [`wpas_plugin_settings`](https://github.com/ThemeAvenue/Awesome-Support/blob/master/includes/admin/class-admin-titan.php#L100), and the whole thing is loaded on the `plugins_loaded` action.

**Comment by d4b** [comment]
When can we expect an update?

**Comment by julien731** [comment]
As soon as the bug is fixed @d4b ;)

**Comment by SiamKreative** [comment]
Hey @d4b I'm just tagging you to make sure you're aware this has been fixed :)

**Comment by d4b** [comment]
fixed :)
