### ISSUE TITLE
Show ticket actions on frontend

### ISSUE THREAD

**Issue by TheZoker** [ThemeAvenue/Awesome-Support#76]
Show actions also on frontend view between the ticket replies, so same as in backend (e.g status is changes, agent assigned another agent to the ticket, agent was assigned to the ticket (may directly after the ticket creation)).

**Comment by julien731** [comment]
Do you mean you'd like to have the entire ticket history displayed to the user also or just show the history on front-end for agents only?

**Comment by TheZoker** [comment]
For the user also, so he can follow the process :)
(May its better if that option is optional)

**Comment by julien731** [comment]
We have decided that this won't be implemented in core because we believe is doesn't bring a real value to the users and might confuse them. However, we've added a new filter [`wpas_replies_object_args`](https://github.com/ThemeAvenue/Awesome-Support/commit/c668cc87ab742b53a7b5b69950157db433061750) which allows you to modify the arguments of the global `$wpas_replies` object. If you want to display the history on front-end you just need to add `ticket_history` to the `post_type` argument.
