### ISSUE TITLE
Cant add custom fields

### ISSUE THREAD

**Issue by TheZoker** [ThemeAvenue/Awesome-Support#83]
According to this tweet, I cant add custom fields in the latest version 3.x
https://twitter.com/_AwesomeSupport/status/564811956901539840

**Comment by julien731** [comment]
That is correct. I will prepare a first draft of the doc for that part asap.

**Comment by TheZoker** [comment]
Can you may tell me what I have to change to get it work?
https://gist.github.com/TheZoker/6643dc1f9f15086bf01e

**Comment by julien731** [comment]
I'm sorry but I'll have to get back to you tomorrow about this. I'm not at the office and I'll need to check a few things before telling you anything. I don't want to give you false indications.

**Comment by julien731** [comment]
I have just tested your code and it works correctly for me. I have added it to the theme's `functions.php` file and gave the field a name (what is `$page_url` in your example?).

Please note that the first parameter is the field ID and should be a text string. Here is an example:

`
wpas_add_custom_field( 'site_url', array( 
	'title'    => 'Website URL',
	'log'      => true,
	'required' => true,
	'callback' => 'url' )
);
`

I have added the `url` field type in the core (will be available with 3.1.3) so that you don't have to do all the checking and data retrieval.

**Comment by TheZoker** [comment]
I updated to the latest 3.1.3, but the url field does not show up :/
(I can send you login data via email, so you can try it yourself)

**Comment by holy88** [comment]
I've added a custom field in the ticket section with a lot a lot a lot of headache .. will paste here "how to" if it's ok for julien

**Comment by julien731** [comment]
Of course @holy88 no problem. I am surprised that this gave you such a headache... It's supposed to be very straightforward! It is because of the lack of documentation (shame on me) or was the code a problem?

**Comment by SiamKreative** [comment]
Guys @TheZoker @holy88 I'm closing this issue as we just published the [documentation for custom fields](http://getawesomesupport.com/documentation/awesome-support/custom-fields/). I'd love to have your feedback on the documentation: is it easy to understand? Is it clear enough?
