### ISSUE TITLE
Use @username for changing assigned agent and tag the agent

### ISSUE THREAD

**Issue by TheZoker** [ThemeAvenue/Awesome-Support#87]
When I use a @agentname in a ticket answer, it would be nice, if that would become a link to the user and also assign the ticket automatically to the named agent.

Thank you

(E.g "I will now hand you over to @johndoe. He will now be your supporter")

**Comment by julien731** [comment]
This sound like a pretty feature, but I am struggling to picture a case where it would really be useful.

First of all, we won't be adding an "automatic transfer" feature. It doesn't make sense to me that tagging someone means transferring a ticket. Tagging and transferring are two different things and shouldn't be mixed. I can already hear support requests like "I replied to a ticket and now I don't see it anymore" because another agent was tagged and the support staff didn't know it would transfer the ticket.

Now regarding the tagging itself, the first thing to note is that it can't come alone. It would be useless to tag someone and then nothing happens except the clickable username. This means that we need to introduce a notification system internally for agents.

This initially sounds like a small feature but in fact it will require a lot of changes and development. I'd be happy to hear more feedback about it but I think we'll leave this on the side for know, and if more users ask for it then we might consider it more seriously.

**Comment by SiamKreative** [comment]
*Maybe this should be part of the [notification add-on](http://getawesomesupport.com/addons/notifications/)  for Awesome Support.*

To me, tagging someone should only be used to notify someone (like it does here on Github). If we add this feature to the add-on, I think we should use Slack / Pushbullet to actually notify the user that has been tagged. We could do it internally within WordPress using the Hearbeat API though, but it would require more work.

What do you think @TheZoker ?

**Comment by TheZoker** [comment]
Yea I guess that would be a good idea, but how do you want to notify a single person via slack instead of pushing to a channel?
