### ISSUE TITLE
eMail Addon question

### ISSUE THREAD

**Issue by TheZoker** [ThemeAvenue/Awesome-Support#88]
I see the email addon is near to be published.

So is it possible with it to manage the following situation:

Client sends a email
a) Client has an account (email ticket = email client) -> the ticket is assigned to him (ticket status switches to open/new)
b) Client does not have an account -> the ticket is created with status "unregistered", the client does get an email explaining that he needs to register an account with the email he used to send this ticket. The system now checks every new signed up user, if he is the one, that send the email (email ticket = email client). If the client is the one -> assign the ticket to him (ticket status switches to open/new)

Additional the support team needs an option to manually assign a ticket to client with the status "unregistered", because the client may signed up with another email address by mistake.

Thank you

**Comment by julien731** [comment]
With the first version, incoming e-mail will only be processed as replies to existing tickets. If an e-mail can't be attached to a ticket, an admin will have to manually review it and decide what to do with it.

In a future version we will add the ability to create a new ticket directly by sending an e-mail. However, we will need to make some changes to the core first, that's why it's not going to be in v1 of the e-mail addon.

Your suggestion of creating a new ticket if the sender is a known user is quite good and could be a nice improvement while waiting for full ticket creation by e-mail. We will think about it and try to plan it for the next release.
